version: '3.3'

services:
  backend:
    build: .
    environment:
      - BOOKMARKS_SECRET_KEY=mysupersecretkey
      - BOOKMARKS_BACKEND_DOMAIN=localhost
      - BOOKMARKS_FRONTEND_BASE_URL=http://localhost:3000
    ports:
      - "8000:80"
    volumes:
      - "./database:/database"
